
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SB_URL=Deno.env.get("SUPABASE_URL")!,SB_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const H={apikey:SB_KEY,Authorization:"Bearer "+SB_KEY,"Content-Type":"application/json"};
const ASSETS=["BTC","ETH","SOL","BNB"],FROM=1735689600,TO=1788220800,COST=.00065;
type B={t:number,o:number,h:number,l:number,c:number}; type T={asset:string,t:number,R:number};
async function load1h(a:string){const out:B[]=[];for(let off=0;;off+=5000){const r=await fetch(SB_URL+"/rest/v1/rpc/bt_bloque2",{method:"POST",headers:H,body:JSON.stringify({p_activo:a,p_tf:"1h",p_off:off,p_lim:5000})});if(!r.ok)throw new Error(a+" "+r.status);const j=await r.json() as number[][];for(const x of j)out.push({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4]});if(j.length<5000)break}return out.sort((a,b)=>a.t-b.t)}
function agg4(src:B[]){const m=new Map<number,B[]>();for(const b of src){const k=Math.floor(b.t/14400)*14400;if(!m.has(k))m.set(k,[]);m.get(k)!.push(b)}return[...m.entries()].sort((a,b)=>a[0]-b[0]).map(([t,a])=>{a.sort((x,y)=>x.t-y);return{t,o:a[0].o,h:Math.max(...a.map(x=>x.h)),l:Math.min(...a.map(x=>x.l)),c:a.at(-1)!.c}})}
function ema(v:number[],n:number){const o=new Array(v.length).fill(NaN),k=2/(n+1);let e=v[0];for(let i=0;i<v.length;i++){e=i?v[i]*k+e*(1-k):v[i];o[i]=e}return o}
function atr(b:B[],n=14){const tr=b.map((x,i)=>i?Math.max(x.h-x.l,Math.abs(x.h-b[i-1].c),Math.abs(x.l-b[i-1].c)):x.h-x.l),o=new Array(b.length).fill(NaN);let s=0;for(let i=0;i<tr.length;i++){s+=tr[i];if(i>=n)s-=tr[i-n];if(i>=n-1)o[i]=s/n}return o}
function stats(t:T[]){const r=t.map(x=>x.R),n=r.length;if(n<2)return{n};const m=r.reduce((a,b)=>a+b,0)/n,sd=Math.sqrt(r.reduce((s,x)=>s+(x-m)**2,0)/(n-1));let w=0,gp=0,gl=0,eq=0,peak=0,dd=0;for(const x of r){eq+=x;peak=Math.max(peak,eq);dd=Math.min(dd,eq-peak);if(x>0){w++;gp+=x}else gl+=-x}const k=Math.floor(n/3);return{n,mean_R:m,t:sd?m/(sd/Math.sqrt(n)):0,win_pct:100*w/n,profit_factor:gl?gp/gl:null,total_R:eq,max_drawdown_R:dd,terciles:[r.slice(0,k),r.slice(k,2*k),r.slice(2*k)].map(a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null)}}
function manage(b:B[],start:number,entry:number,stop0:number,risk:number,A:number[],mode:string){let stop=stop0,real=0,size=1,partial=false,exit=Math.min(start+120,b.length-1);for(let j=start;j<=exit;j++){const x=b[j];if(x.h>=stop)return{g:real+size*((entry-stop)/risk),exit:j};const r1=entry-risk,r15=entry-1.5*risk;if(mode==="tp1"&&x.l<=r1)return{g:1,exit:j};if(mode==="tp15"&&x.l<=r15)return{g:1.5,exit:j};if(!partial&&x.l<=r1&&(mode==="p50_c5"||mode==="p33_c5"||mode==="p33_atr")){const frac=mode==="p50_c5"?.5:1/3;real+=frac;size=1-frac;partial=true;stop=entry}
 if(partial&&mode==="p33_atr")stop=Math.min(stop,x.c+1.5*A[j]);
 const n=(mode==="p50_c5"||mode==="p33_c5")?5:10;const ch=Math.max(...b.slice(Math.max(0,j-n),j).map(z=>z.h));if((mode==="p50_c5"||mode==="p33_c5"||mode==="p33_atr")&&x.c>ch)return{g:real+size*((entry-x.c)/risk),exit:j}}
 const x=b[exit];return{g:real+size*((entry-x.c)/risk),exit}}
function run(asset:string,b:B[],mode:string){const C=b.map(x=>x.c),E=ema(C,200),A=atr(b),out:T[]=[];let cool=-1;for(let i=220;i<b.length-2;i++){const x=b[i];if(x.t<FROM||x.t>=TO||i<=cool)continue;const ll=Math.min(...b.slice(i-20,i).map(z=>z.l));if(!(x.c<ll&&x.c<E[i]&&(ll-x.c)>=.50*A[i]))continue;const entry=b[i+1].o,stop=x.c+2*A[i],risk=Math.abs(entry-stop),rp=risk/entry;if(!(risk>0)||rp<.003||rp>.08)continue;const s=manage(b,i+1,entry,stop,risk,A,mode);out.push({asset,t:b[s.exit].t,R:s.g-(2*COST)/rp});cool=s.exit}return out}
Deno.serve(async()=>{try{const modes=["tp1"],raw:Record<string,B[]>={};for(const a of ASSETS)raw[a]=agg4(await load1h(a));const res:any={};for(const m of modes){const all:T[]=[],by:any={};for(const a of ASSETS){const tr=run(a,raw[a],m);by[a]=stats(tr);all.push(...tr)}all.sort((a,b)=>a.t-b.t);res[m]={overall:stats(all),by_asset:by}}return new Response(JSON.stringify({ok:true,period:"2025-01-01 to 2026-08-31 recent holdout",entry:"PA v2 short fixed",results:res}),{headers:{"content-type":"application/json"}})}catch(e){return new Response(JSON.stringify({ok:false,error:String((e as any)?.message||e)}),{status:500,headers:{"content-type":"application/json"}})}});
